production:
  FB05_HOST: 0.0.0.0
  FB05_PORT: 8080
  GET_TIMEOUT: 10
development: &development
  # App
  FB05_HOST: localhost
  FB05_PORT: 8080
  GET_TIMEOUT: 5
  # Database
  FB05_DB_USER: fb05_dev
  FB05_DB_PASSWORD: password
  FB05_DB_HOST: localhost
  FB05_DB_PORT: 5432
  FB05_DB_NAME: fb05_development
test: &test
  <<: *development
  # Database
  FB05_DB_NAME: fb05_test