apiVersion: apps/v1
kind: Deployment
metadata:
  name: fb05
spec:
  selector:
    matchLabels:
      app: fb05
  replicas: 1
  template:
    metadata:
      labels:
        app: fb05
    spec:
      containers:
        - name: fb05
          image: angusgmorrison/fb05:latest
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3
